### ISSUE TITLE
Depend on openssl directly.

### ISSUE THREAD

**Issue by twistor** [cweagans/mcrypt-polyfill#13]
I think that depending on phpseclib is a mistake. While this is a shim, openssl is the only real alternative.

**Comment by cweagans** [comment]
I didn't think openssl provided all of the ciphers and such that we need in order to call it a full polyfill. I'm happy to be wrong, of course. If we can get away with not using phpseclib, I'm happy. Been meaning to get back around to this project since mcrypt is being removed from PHP.

**Comment by cweagans** [comment]
I was thinking about this more recently. What if we only have a hard dependency on OpenSSL and only implement the ciphers and modes that it supports. If a caller requests an unsupported cipher or mode, then we throw an exception. If phpseclib is installed, then we can use it for any additional ciphers/modes that openssl doesn't support. I'd be okay with not doing the latter part of that immediately, so we'd just be depending on openssl right now.

**Comment by cweagans** [comment]
See README.md.
